### ISSUE TITLE
Run saved JSON specification from code

### ISSUE THREAD

**Issue by rmanjusha** [serverlessworkflow/synapse#362]
**What is the question**:

Please provide an example on how to read workflow specification JSON and run programmatically .

**Comment by JBBianchi** [comment]
Hello,

A Swagger (OpenAPI) doc should be available under /api/doc but isn't at the moment due to a wrong configuration in the server start up.

In the meanwhile, you can inspect what the dashboard is doing using your browser's dev console.

For instance, getting the info of a workflow is done via a GET request on `/api/v1/workflows/{workflow-id}` and starting a workflow can be done with a POST to `/api/v1/workflow-instances` with:
```json
{
  "workflowId":"helloworld:1.0",
  "inputData":{},
  "autoStart":true
}
```

**Comment by rmanjusha** [comment]
The URLs isn`t working for me . I used yaml - (https://github.com/serverlessworkflow/synapse/blob/main/deployment/docker-compose/eventstore%2Bmongo.yml) for docker compose. 

Browser console shows error with /api urls . Am I missing something with set up ?

![image](https://github.com/serverlessworkflow/synapse/assets/61468185/a837e58e-dce7-4c37-9487-7f8760e8c7cf)

**Comment by JBBianchi** [comment]
Afaik those errors just mean there is no report (and probably no workflow run) for that day.

What's the result of a GET request on http://localhost:42286/api/v1/workflows/{workflowId} ?

**Comment by rmanjusha** [comment]
Here is the message  when trying to access document URL . 

![image](https://github.com/serverlessworkflow/synapse/assets/61468185/0ad17c4c-16f3-4278-a6b6-02b0cf8e9457)

The screenshot I provided is when trying to save a workflow


![image](https://github.com/serverlessworkflow/synapse/assets/61468185/eb26654e-0a4a-4fa1-9c11-eddd0069f463)

**Comment by cdavernas** [comment]
Closed as stale
