### ISSUE TITLE
For some reason I can not save workflows and there is an error popping up 

### ISSUE THREAD

**Issue by viperbmw** [serverlessworkflow/synapse#369]
<img width="973" alt="Screenshot 2024-08-23 at 6 27 43 PM" src="https://github.com/user-attachments/assets/126c78f1-fae1-4ddd-8763-9945592d62c6">

When I make a workflow it will not save I am running in k8s Cluster using the three node deployment. 

When I run native or Docker I still am not able to save workflows........

<img width="1438" alt="Screenshot 2024-08-23 at 6 30 28 PM" src="https://github.com/user-attachments/assets/01448914-2045-4bc9-805a-9bbe95faf54c">

Error in the API auth? 

ail: Synapse.Apis.Management.Http.SynapseHttpManagementApiClient[0]
      An error occured while creating a new workflow: {"auth":["JSON is valid against no schemas from 'oneOf'."],"events":["JSON is valid against no schemas from 'oneOf'."]}

<img width="1022" alt="Screenshot 2024-08-23 at 6 36 21 PM" src="https://github.com/user-attachments/assets/729c2911-7dcc-4c09-bcc0-8ad8750db725">

I did have to add 
`          - name: EVENTSTORE_ALLOW_UNKNOWN_OPTIONS
               value: 'true'
`

for the event-store pod

**Comment by cdavernas** [comment]
Hello @viperbmw, and thanks for reporting!

> An error occured while creating a new workflow: {"auth":["JSON is valid against no schemas from 'oneOf'."],"events":["JSON is valid against no schemas from 'oneOf'."]}

It looks to me like you are defining an invalid/unsupported authentication in your flow.

> I did have to add
         - name: EVENTSTORE_ALLOW_UNKNOWN_OPTIONS value: 'true'
for the event-store pod

Doesn't surprise me, as EventStore has changed most of its parameters since that release of Synapse.

---

I won't be able to help further before next week, as all versions other than `1.0.0-alpha1` (functional WIP) are being discontinued because of the Serverless Workflow refactor.

**Comment by viperbmw** [comment]
Ok I will look at it again and try. Is there as plan on an updated release?

**Comment by cdavernas** [comment]
`1.0.0-alpha1` will be released in upcoming days, but there are no plans to further update previous, discontinued versions.

**Comment by cdavernas** [comment]
Could you identify the problem and/or make your workflow work as expected? Feel free to contribute to branch `0.4.3` if you want to address the underlying issue.

In the meanwhile, I'm gonna close this issue as won't fix because, as said above, versions before `1.x.x` are discontinued. Please do feel free to reopen in case you want to address by contributing, though.
